### ISSUE TITLE
States

### ISSUE THREAD

**Issue by Mobilpadde** [Collinux/GoHue#1]
I love this library, except for one thing... Why isn't [`LightState`](https://github.com/Collinux/GoHue/blob/master/light.go#L43) and [`State`](https://github.com/Collinux/GoHue/blob/master/light.go#L20) within [`Light`](https://github.com/Collinux/GoHue/blob/master/light.go) the same thing?

**Comment by Collinux** [comment]
@Mobilpadde I thought it would be more straightforward to use the `Light.SetState` function with a separate `LightState` struct that has extra variables which apply only to temporary changes in the state (separating variables that end in "increment"). This interface well with [Philips' Set Light State Method](http://www.developers.meethue.com/documentation/lights-api#16_set_light_state). I was trying to keep it in line with Philips' official bridge documentation and not cram everything into the light struct.

I'm open for suggestions though.

**Comment by Mobilpadde** [comment]
Ah, I get that. But why is `Hue` in `LightState` an `int16` but an `int` in `State`?

**Comment by Collinux** [comment]
@Mobilpadde good catch, `Hue` should be `uint16` and `Saturation` should be `uint8` in `State`.

**Comment by Mobilpadde** [comment]
Hurray, I'm useful!

**Comment by Collinux** [comment]
I'm traveling for the next 2 months so I don't have my hardware to do a full test sweep with the changes. Even though it's small I don't want to risk breaking anything. If you want to do a PR with the changes and run all the test files then awesome, otherwise it's no problem and I'll get to it when I have my hardware.

**Comment by Mobilpadde** [comment]
I don't think I'm the right person for this, as I'm no good at golang :c - Maybe later though!

**Comment by Collinux** [comment]
@Mobilpadde I like your "HueBeat" project, it's a great example of a use case for the library. Can I put a link to your repo on the GoHue readme? I would like to start a section titled "See this library in action!"

**Comment by Mobilpadde** [comment]
Oh, please do so! Thanks!

**Comment by Collinux** [comment]
Fixed in commit 541bfc66cb1dd94c9ab4d7089adc0f31a77799d4. Thanks!
