### ISSUE TITLE
Remove hard-coded IP and user token from test files

### ISSUE THREAD

**Issue by Collinux** [Collinux/gohue#3]
Currently I have all of my settings hard-coded into the test files, such as the IP address of my test bridge and my user token to log into the bridge.

I can enhance these test files by doing the following:
1. Use `FindBridges()` and use the 0 index to get the test bridge in all testing files
2. Add a file to .gitignore that includes my user token
- Note: Instructions would have to be included so contributors will know how to run test cases on their own

**Comment by inhies** [comment]
You could also implement a test http server and serve saved responses from a real device

https://golang.org/pkg/net/http/httptest/#example_Server

**Comment by Collinux** [comment]
@inhies I like this idea, though nothing beats having the legit hardware next to you :)
I'll look into it

**Comment by Collinux** [comment]
Added environment variable HUE_USER_TOKEN which must be set in order to run the *_test.go files.
27862f32c233b3a421ac02334bbde48ce937e5e3
